apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-observability-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-observability
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default