name: Deploy
on:
  workflow_run:
    workflows: [Build Test and Push]  # <- nome exato do CI
    branches:
      - main
      - staging
    types: completed

jobs:
    deploy-app:
        runs-on: ubuntu-latest
        outputs:
            tag: ${{ steps.tag.outputs.TAG }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Google Cloud Authentication
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY_GKE }}

            - name: Google Cloud SDK setup
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Get GKE credentials        
              uses: 'google-github-actions/get-gke-credentials@v2'
              with:
                  cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
                  location: ${{ secrets.GCP_REGION }}

            - name: Helm Install
              run: |
                curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

            - name: Image tag definition
              id: tag
              run: |
                echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

            - name: Deploy Application Manifests
              working-directory: ./k8s
              env:
                GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
                GCP_REGION: ${{ secrets.GCP_REGION }}
                GCP_ARTIFACT_REPO: ${{ secrets.GCP_ARTIFACT_REPO }}
                IMAGE_TAG: ${{ steps.tag.outputs.TAG }}
              run: |
                envsubst < deployment.yaml | kubectl apply -f -
                kubectl apply -f service-app.yaml
                kubectl apply -f ingress.yaml
                kubectl apply -f service-observ.yaml

            - name: Deploy Service Monitor and Prometheus Rule
              working-directory: ./monitoring/prometheus
              run: |
                kubectl apply -f service-monitor.yaml

            - name: Deploy Prometheus Rule for Python App
              working-directory: ./monitoring/prometheus
              run: |
                kubectl apply -f prometheusrule-python-app.yaml

            - name: Upgrade helm chart for Alertmanager and Grafana
              working-directory: ./monitoring
              run: |
                helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
                helm repo update
                helm upgrade --install my-kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 76.3.0 \
                  -n monitoring -f values.yaml

            - name: AlertmanagerConfig Deploy
              working-directory: ./monitoring/alertmanager
              run: |
                kubectl apply -f alertmanagerconfig-webhook.yaml

            - name: External Secrets Operator (ESO) Install
              run: |
                helm repo add external-secrets https://charts.external-secrets.io
                helm repo update
                helm upgrade --install external-secrets external-secrets/external-secrets \
                  --namespace external-secrets \
                  --create-namespace \
                  --set installCRDs=true

            - name: Agurda os CRDs ficarem disponiveis
              run: |
                kubectl wait --for=condition=Established --timeout=180s \
                  crd/secretstores.external-secrets.io \
                  crd/clustersecretstores.external-secrets.io \
                  crd/externalsecrets.external-secrets.io

            - name: SecretStore and ExternalSecret Deploy
              working-directory: ./monitoring/grafana
              env:
                GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
              run: |
                envsubst < secret-store.yaml | kubectl apply -f -
                kubectl apply -f external-secret-grafana.yaml -n 


            - name: Mostra em qual cluster o runner está mexendo
              run: |
                kubectl config current-context
                kubectl cluster-info


            - name: Confere se os CRDs existem e a versão do apiVersion
              run: |
                kubectl get crd | grep external-secrets || true
                kubectl api-resources | grep -i external-secrets || true
                kubectl get crd secretstores.external-secrets.io -o jsonpath='{.spec.versions[*].name}{"\n"}' || true